/* JSONです */
const data = [
    { "next_scene_index": -1, "type": "scene change", "background": "home_outside" },
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "俺の名前は{$player_name}。\nその辺にいる普通の高校2年生だ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "3月31日。\n俺は親の転勤の都合で三重県？市に引っ越してきた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "この街には小さいころ住んでいたことがある。\nこの数年は他の県を転々としてきた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "そのため、三重に関する知識はうろ覚えだ。"},
    { "next_scene_index": -1, "type": "scene change", "background": "room01" },
    { "next_scene_index": -1, "type": "dialogue", "background": "room01", "speaker": null, "message": "引っ越しの荷解きは大体終わり、\n部屋には細々とした荷物の入った段ボールが残る。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room01", "speaker": null, "message": "《ピンポーン》\n家のチャイムが鳴った。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room01", "speaker": null, "message": "これがこの家のチャイムの音か。\n家にはあいにく自分しかいないので、階段を駆け下りてドアを開けた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "？？？", "message": "…{$player_name}くん？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "どこか懐かしく、そして聞き覚えのある声がする。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "はい。そうですが。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "？？？", "message": "私のこと、覚えとるー？\n会うん10年ぶりかも。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "ここで覚えていないと言うのは誰であっても失礼だろう。\nそしてまもなくこの聞き覚えのある声と面影のある姿で思い出した。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "{$B_name}。\n久しぶり。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "{$B_name}はかつて俺がこの街に住んでいた頃の幼馴染だ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "今もその頃の面影はあるが、\n俺の思い出に残るそれとは大きく異なっていた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "すっかり変わってしまって、正直驚きしかない。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "すっかり変わってしまって、ホント驚いた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "ん？\n何か言った？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "……声に出てしまっていた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "何か考えとったん？\n明日からの新しい高校生活とか？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "「転校生」、憧れるわあ。\n「転校生」って響きがいいよね。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "実際は大変なだけだよ。\n友達も一から作らなきゃいけないし。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "ええー。そうなん？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "既に完成されたコミュニティに一人立ち向かっていくのは\nものすごく気怠いし気まずいんだよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "う、うん。ごめんごめん。\n新しい地で新しい出会い。新しい恋もあるかもよ？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "からかうなって。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "正直なところ、\n内心では新生活を楽しみにしている。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "{$player_name}くんやったら、すぐ皆と仲良くなるんやろなあ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "そうなるといいけど。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "今までの転校生活でも\nなんだかんだ上手くクラスに馴染んできたので自信はある。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "あ、{$player_name}くん忙しい時にごめんね。\nじゃ、私はこの辺で。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "明日から、\n……よろしくお願いします。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "そう言い残し、{$B_name}は帰っていった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "それにしてもあの{$B_name}がこんな美人になっていたなんて。\n昔の姿を思い出して幾度となく驚く。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "さっさと荷物の整理と明日の準備をして、\n今日は早く寝ることにしよう。"},
    { "next_scene_index": -1, "type": "scene change", "background": "room02" },
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "明日はどんな出会いがあるだろうか。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "若干の不安と期待が、心の中で渦を描いている。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": "{$player_name}", "message": "寝て起きれば朝だ。\n早く眠りにつこう。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "俺は目を閉じ、\n夢の世界に身を預けることにした。"},

    { "next_scene_index": -1, "type": "scene change", "background": "home_outside" },
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "-翌日-"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "すごく気持ちのいい朝だ。\n良いスタートを切れそうな予感がする。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "登校する時刻になり、ドアを開けた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "！？！？！？！？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "{$B_name}、ここで何してるんだ！？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "ドアを開けた先には{$B_name}が立っていた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "いや…\n今日から毎日一緒に登校できるって思って。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "えっ。\nラブコメのヒロインかよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "はよ行かんと遅刻するに？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "じゃあ俺は一人で行く。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "それはありえやん、ありえやんから。"},

    { "next_scene_index": -1, "type": "scene change", "background": "road01" },
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "…なぜか俺は{$B_name}と一緒に登校することになった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "まさか{$player_name}くんが\n10年ぶりに三重に帰ってくるなんて。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "俺もビックリだよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "それにしても、この辺の見慣れた景色も\n微妙に変わってる気がする。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "そこのイオンも名前変わっちゃったり。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "へえ。\n昔からあんなに親しまれてたのに。残念だ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "ビックリでしょー？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "いろんなものが変わっていく中！\n{$player_name}くんに朗報です！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "なになに？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "私の好きなものは変わっておりません！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "演説かよ。\n政治家でも目指してるのか？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "そういえば昔から{$B_name}が好きなものあったよな…。\nなんだっけ…。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "{$B_name}って「コレ」好きだったよな！"},
    { "next_scene_index": -1, "type": "question", "background": "road01", "options": ["安倍川餅", "赤福", "ずんだもち"], "answer": 1, "answer_next_scene_index": 72, "incorrect_next_scene_index": 69 },
    { "next_scene_index": -1, "type": "dark dialogue", "background": "", "speaker": null, "message": "「私が三重名物の赤福大好きやって知っとってそんなこと言っとるん？」\n{$B_name}は突如として激昂し始めた。\n「もう知らん」\n彼女はそう言い残し、一人で学校に向かっていった。\n\n昔から、怒り狂ってしまった彼女は何をしでかすか分からない。\n早くなんとかしないと。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "", "speaker": "{$B_name}", "message": "背後に気配を感じる。体を押さえつけられ、口の中に何かが詰められていく。\n甘い。\n視界が歪む。\n餅が口の中に次々と詰められ、息ができなくなっていく。\n徐々に意識が遠のいていく。\n\nうっすら声が聞こえる。\n\n「ね、美味しいでしょ。もっと三重のこと勉強しとかなあかんに」"},
    { "next_scene_index": 66, "type": "bad end", "h2": "BAD END 1", "message": "{$player_name}は窒息してしまいました。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "三重県民やもん。当然やん。\n「赤福」はお茶とめっちゃ合うんやに？"},
    { "next_scene_index": -1, "type": "supplement", "h2": "おみやげの定番\n「赤福」", "message": "お伊勢参りのお土産として人気の赤福餅。実は名古屋駅でも買えてしまいます。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "しかし「赤福」っておみやげのイメージが強いから\n普段はあんまり食べないんじゃないか？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "よく分かっとるやん。\nでもたまに食べるからいいんかも。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "それからバスに乗り、おみやげ話をしていると\n俺が今日から通う高校に着いた。"},

    { "next_scene_index": -1, "type": "scene change", "background": "school_entrance" },
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": null, "message": "昇降口は、新学年・新学期ということもあって\n活気に満ちあふれている。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": null, "message": "クラス替えの紙に釘付けになっている生徒や、\nクラス替えがなく、そのまま教室に向かう生徒の姿。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": null, "message": "俺は2年3組に編入することになっている。\nいわゆる文系クラスだ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$B_name}", "message": "私は理系やから2年1組。\n文系にしとけばよかったかなあ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$player_name}", "message": "勉強する内容が違うんだから\n仕方ないだろ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$B_name}", "message": "しょうみ、このタイミングで文系・理系って適性分からんし、\nどうせ将来忘れちゃうからどっちでも良いっちゃ良いんやけど。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$player_name}", "message": "そうだよな。\n実際理系だと文転する人も多いし。ほどほどに頑張ろう。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$B_name}", "message": "いやいや基礎学力と思考力の育成は大事やに！\n大人になって勉強し続けるときに役立ちそうやし！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$player_name}", "message": "どっちだよ。\nあと人生二周目かよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": null, "message": "俺は教室へと向かった。"},

    { "next_scene_index": -1, "type": "scene change", "background": "school_classroom" },
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": null, "message": "クラスには、友人同士で話す者や一人でスマホを弄る者など\n様々な生徒の姿があった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": null, "message": "黒板に掲示されたプリントを手掛かりに\n自分の席を見つけ、座った。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": null, "message": "隣の席を見ると、いかにもな陽キャが座っていた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "おはよう。\nお前が噂の転校生かーｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": null, "message": "話しかけてくれるのはありがたいが、\nその態度はとても馴れ馴れしい。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "俺の名前は{$C_name}。\nよろしくｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "俺は{$player_name}って言います。\nよろしくお願いします。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "自分、めっちゃ硬いやんｗ\n敬語やめろやｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "…ごめん。\nこれからよろしく。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "何か弄り甲斐ありそうやわーｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "よし、じゃあ俺がこのクラスの友達第1号になったろか？ｗ\nただし…"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "ただし…？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "先週、俺が行ってきたとこ当てれたらやなｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "分かった。\n当ててみせよう。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "お、乗り気やんｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "ソーセージ作り、楽しかったでｗ\nさあどれや！ｗ"},
    { "next_scene_index": -1, "type": "question", "background": "school_classroom", "options": ["モクモクファーム", "鈴鹿サーキット", "青山高原"], "answer": 0, "answer_next_scene_index": 109, "incorrect_next_scene_index": 106 },
    { "next_scene_index": -1, "type": "dark dialogue", "background": "", "speaker": null, "message": "「お前、何言っとんの？」\n{$C_name}の目は開きっぱなしだ。まるで奇妙なものを見るかのように俺のほうに視線を向け続けている。\n「申し訳ないけど、お前と友達になれそうにないわ。ごめん。他を当たってくれ」\n彼はそう言い残し、他の友人の席へと向かっていった。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "", "speaker": null, "message": "俺はこの出来事がきっかけとなり、気がおかしくなった。\n高校にも行かなくなった。\n{$B_name}とも関わらなくなった。\n誰とも会話をしなくなった。\n\nもしあの時、三重のことをもっと知っていたら。"},
    { "next_scene_index": 104, "type": "bad end", "h2": "BAD END 2", "message": "{$player_name}は鬱になってしまいました。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "そう！ｗ\n我ながら上手に出来て美味かったでｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "今度家族で行くときに\n連れてったるわｗ"},
    { "next_scene_index": -1, "type": "supplement", "h2": "手づくり体験なら\nモクモクファーム", "message": "伊賀市の「モクモク手づくりファーム」。ブタを見た後にバーベキューができます。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": null, "message": "チャイムが鳴り、転校生の俺が担任から紹介される。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "××から転校してきた{$player_name}といいます。\nよろしくお願いします。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": null, "message": "紹介はあっさり終わった。\n生徒たちは始業式のため、体育館に向かう。"},

    { "next_scene_index": -1, "type": "scene change", "background": "school_entrance" },
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": null, "message": "始業式やLHRが終わり、午前で放課となった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$player_name}", "message": "まさか初日から課題が出るとは思わなかったし\n帰ってさっさと終わらせるか。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$B_name}", "message": "遅い！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$player_name}", "message": "うわあ！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": null, "message": "{$B_name}は昇降口で俺を待っていた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$B_name}", "message": "驚いたー？\nじゃ、一緒に帰ろっか。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$player_name}", "message": "俺は一人で帰る。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_entrance", "speaker": "{$B_name}", "message": "なに冗談言っとるん？\n方向一緒やん。"},

    { "next_scene_index": -1, "type": "scene change", "background": "road01" },
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "…俺は{$B_name}と一緒に下校することになった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "{$player_name}くん、\nちょっとコンビニ寄ろ？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "ああ、いいよ。"},

    { "next_scene_index": -1, "type": "scene change", "background": "store" },
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$player_name}", "message": "…コンビニ？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "みんなコンビニって呼んどるよー。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$player_name}", "message": "まあいいや。\n何買うの？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "うーん\n適当に。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "あ、いいこと思いついた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "{$player_name}くんにお菓子おごったげる。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$player_name}", "message": "え、マジで。\nいやいや俺がおごるよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "いや、私がおごるに。\nただしこのクイズに正解したらね。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$player_name}", "message": "分かった。\n面白いじゃん。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "じゃあ問題です。\n三重県にあるのはどれでしょう？"},
    { "next_scene_index": -1, "type": "question", "background": "store", "options": ["日本モンキーパーク", "愛知牧場", "名古屋アンパンマンこどもミュージアム&パーク"], "answer": 2, "answer_next_scene_index": 143, "incorrect_next_scene_index": 140 },
    { "next_scene_index": -1, "type": "dark dialogue", "background": "store", "speaker": null, "message": "「えっ、冗談やろ？」\n{$B_name}は思いつめた表情で俺を見つめる。\n\n「じゃあ私、この店の商品ぜーんぶ欲しい。勝負に負けたんやから、これくらい当然やんな」\n{$B_name}の目は本気だ。ただしその言葉には一切感情がないようにも思えた。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "store", "speaker": null, "message": "俺の現在の所持金、そして貯金では到底賄えきれないほどの品揃えだった。\n「今回のお代は、絶対にすべてお支払いしますから…」\n\n俺はその日から毎日、店主に頭を下げ続ける事態となった。"},
    { "next_scene_index": 138, "type": "bad end", "h2": "BAD END 3", "message": "{$player_name}は破産してしまいました。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "正解！\n「ナガシマスパーランド」の横にあるんやにー。"},
    { "next_scene_index": -1, "type": "supplement", "h2": "名古屋を名乗らされる\n三重", "message": "名古屋アンパンマンこどもミュージアムは三重県桑名市にあります。名古屋まで約40km。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "じゃあ私がお菓子おごったげる。\n…あ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$player_name}", "message": "どうした？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "…財布、家に忘れたんやった。\nごめーん。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$player_name}", "message": "…レジに行く前に気付いて良かったな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": null, "message": "結局、俺が二人分のお菓子を買った。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$B_name}", "message": "明日ゼッタイ返すから！\nゼッタイ！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": "{$player_name}", "message": "別にいいって。\n…じゃあ今度また俺がクイズを出すからそれの出来次第な。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": null, "message": "{$B_name}のお茶目だが真面目な性格は\n昔から変わっていない。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "store", "speaker": null, "message": "ただ、昔抱いた感情とは違う。\nそんな{$B_name}を気になっている自分がいた。"},

    { "next_scene_index": -1, "type": "scene change", "background": "home_outside" },
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "初めての登校と下校を経て、\n帰宅。"},
    { "next_scene_index": -1, "type": "scene change", "background": "living" },
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "新しい高校、どうだった？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "{$player_name}", "message": "まあまあかな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "それより{$B_name}ちゃんと一緒に登校したんでしょ？\nホント美人さんになったよね。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "{$player_name}", "message": "……"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "もしかしてもう惚れちゃってんの？\n付き合ったら報告してよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "{$player_name}", "message": "そういうんじゃないから。\nやめて。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "あ、そうそう。\nアンタ三重のこと何も知らないでしょ？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "{$player_name}", "message": "昔住んでたし大体知ってるよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": null, "message": "嘘である。\n昔すぎて覚えていないことのほうが圧倒的に多いはずだ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "あ、そう。\nさっきお隣さんから聞いたんだけど、コレ知ってる？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "{$player_name}", "message": "何？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "この中に三重発祥の食べ物があるんだけど…"},
    { "next_scene_index": -1, "type": "question", "background": "store", "options": ["台湾ラーメン", "天むす", "きしめん"], "answer": 1, "answer_next_scene_index": 173, "incorrect_next_scene_index": 170 },
    { "next_scene_index": -1, "type": "dark dialogue", "background": "living", "speaker": null, "message": "「{$player_name}、それは本気で言ってるわけ？」\n俺の親は硬直した。\n「こんな子に育てた覚えはないんだけど。アンタ、本当に{$player_name}？」\n親とは思えない、酷い言葉が浴びせられる。\n\n「ちゃんと勉強や社会経験はさせてきたつもりなのに…」"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "living", "speaker": null, "message": "俺は家を追い出された。何度謝罪しようが、家には二度と入れてもらえなかった。\n{$B_name}の家にも行ってみたが、門前払い。\n当てのなくなった俺はホームレスになった。\nお金もツテもないので、日に日に痩せていく一方であった。"},
    { "next_scene_index": 168, "type": "bad end", "h2": "BAD END 4", "message": "{$player_name}は餓死してしまいました。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "よく知ってたね。\nさすが我が子。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": null, "message": "勘が当たってよかった…。"},
    { "next_scene_index": -1, "type": "supplement", "h2": "天むすは\n三重県発祥の食べ物", "message": "「名古屋めし」として有名な天むすは、三重県津市の発祥と言われています。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "living", "speaker": "親", "message": "当てたご褒美として、\n今夜は{$player_name}の好きな味噌カツにしよう。"},

    { "next_scene_index": -1, "type": "scene change", "background": "room02" },
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "課題や書類の記入をしていたら\nすっかり寝る時間になってしまった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "まだ4月1日だというのに、明日から早速授業が始まる。\nどうやら文科省の方針の影響らしい。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "だが明日からの授業や学校生活、\n正直、期待感しかない状況だ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "新しい高校生活は、良い友人や{$B_name}のおかげで\nなんとかやっていけそうだ。"},

    { "next_scene_index": -1, "type": "scene change", "background": "home_outside" },
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "-翌日-"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "また今日も{$B_name}が家の前で待っていた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "おはよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": "{$player_name}", "message": "おはよう。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "今日の朝も{$B_name}と一緒に登校した。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "なお昨日とは違って、\n俺は{$B_name}の目を直視できなくなっていた。"},
    { "next_scene_index": -1, "type": "scene change", "background": "school_classroom" },
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": null, "message": "しっかり6時間の授業を受け、\nあっという間に放課後になった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "{$player_name}、部活どうするん？ｗ\nどっか入るんか？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "ああ、全然考えてなかった。\n別に帰宅部でも構わないかな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "よーしｗ\n俺が部活見学一緒に回ったるにｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "{$C_name}は部活行かなくていいのか？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$C_name}", "message": "今日バスケ部休みやからｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_classroom", "speaker": "{$player_name}", "message": "そうなんだ。\nお言葉に甘えて付いていくよ。"},

    { "next_scene_index": -1, "type": "scene change", "background": "school_garden" },
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "校内には運動部や演劇部の声、\n吹奏楽部の楽器の音色が響いている。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "{$player_name}は前の高校で\n何部やったん？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "サッカー部だった。\nお遊びの弱小チームだったけど。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "じゃあまずはサッカー部で決まりやなｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "この高校のサッカー部、強豪じゃなかったか？\nもうそこまで本気でやる気はないかな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "とりあえず見に行こやｗ\nな！ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "俺は{$C_name}に半ば強引に\nグラウンドに連れていかれた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "俺と{$C_name}はサッカー部の練習を\n見学させてもらうことになった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "今の縦パスからのドリブルシュート\n半端ないってｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "そんなんできやんやん普通ｗ\nなあ？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "あ、ああ。\nそうだな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "俺が入部できるはずはないので、全然見ていない。\n前の高校とはレベルが段違いなのだ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "グラウンドでは他にも野球部や陸上部など\n様々な部活が行われている。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "ふと視線をずらすと\nテニスコートが見えた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "ぼーっとしていると、\n{$B_name}の練習する姿が見えた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "テニスウェアの{$B_name}に釘付けになる。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "もしもーしｗ\nおーいｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "あ、ごめん。\n何か言った？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "{$player_name}全然サッカー見やんやんｗ\n嫁ばっか見てｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "なっ…！\n嫁って何だよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "図星やんｗ\n{$B_name}ちゃんのこと好きなんやろ？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "いや、好きとか……"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "まあ何でもええわｗ\n俺は味方やからｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "そういや明日\n{$B_name}ちゃんの誕生日ちゃった？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "あー、そういやそうだったか。\nよく知ってるな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "{$B_name}ちゃん校内で有名人やからなｗ\nプレゼントは何渡すん？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "えっ、プレゼント？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "好感度アップのチャンスやんｗ\nこの機会を逃すアホはおらんやろｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "プレゼントするんやったら\nあの三重生まれのアイスがええんちゃう？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "誕生日プレゼントにアイスって…。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "知る人ぞ知る、\n{$B_name}ちゃんの大好物やったと思うにｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "あの三重生まれのアイス…\n名前なんやったっけ？ｗ"},
    { "next_scene_index": -1, "type": "question", "background": "store", "options": ["ガリガリ君", "サクレ", "あずきバー"], "answer": 2, "answer_next_scene_index": 234, "incorrect_next_scene_index": 231 },
    { "next_scene_index": -1, "type": "dark dialogue", "background": "school_garden", "speaker": null, "message": "「何言うとるん？\n頭冷やすか？ちょっと待っとってな」\n{$C_name}は血相を変え、駆けていった。\n俺はぼーっとしていた。部活に入るとか入らないとか、自分の人生にとって重要なことなのだろうか。\n{$C_name}だったら何て言うかな。\n様々な考えが頭を駆け巡る。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "{$C_name}が戻ってきた。第六感が何かを悟っているのか、体が震え出した。\n彼の手にはキンキンに冷えたあずきバー。\n「良い奴やと思とったよ」\n\nその瞬間、俺の頭に強い衝撃が走った。"},
    { "next_scene_index": 229, "type": "bad end", "h2": "BAD END 5", "message": "{$player_name}はあずきバーで殴られ、意識を失ってしまいました。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "そう！ｗ\nあずきバーや！ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": null, "message": "{$B_name}、\n甘いものというより小豆が好きなのかな。"},
    { "next_scene_index": -1, "type": "supplement", "h2": "三重県に本社を置く\n製菓会社", "message": "あずきバーの井村屋、おにぎりせんべいのマスヤ、おやつカンパニーなどは三重の企業。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "あずきバーはいつでもそこのコンビニで買えるだろ？\nもうちょっとプレゼントっぽい物にしようかな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "あずきバーなめとんか？ｗアイスだけに？ｗ\n{$player_name}がそう言うなら買いに行こにｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$player_name}", "message": "ん？最初何か言ったか？\nじゃあ、このまま付き合ってくれるか？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "school_garden", "speaker": "{$C_name}", "message": "早よ行こｗ\n帰り遅くなるんもあれやしｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": null, "message": "俺と{$C_name}はそのままイオンへ向かった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": null, "message": "ところが俺と{$C_name}は、\nあずきバー以外のプレゼントが思い浮かばなかった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": null, "message": "そんな俺たちを見かねた店員にハンドクリームを勧められ、\nそれを購入した。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": "{$C_name}", "message": "これで好感度アップ間違いナシやなｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": "{$player_name}", "message": "今日はありがとな。\nいろいろと付き合ってくれて。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": "{$C_name}", "message": "それより部活はどうすんの？ｗ\nサッカー部入るんか？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": "{$player_name}", "message": "無理無理。絶対ついてけないよ。\n今度文芸部へ見学にでも行ってみようかな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": "{$C_name}", "message": "{$player_name}が～？ｗ\n{$B_name}ちゃんへのプレゼント選ぶセンスも知識もなかったのに？ｗ"},
    { "next_scene_index": -1, "type": "dialogue", "background": "shopping", "speaker": "{$player_name}", "message": "……\n早く帰ろう。"},

    { "next_scene_index": -1, "type": "scene change", "background": "room02" },
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "プレゼント、喜んでくれると良いな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "最初からあずきバーにしておけば\n良かったかな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "room02", "speaker": null, "message": "ただ今更悩んでも仕方ない。\n早く眠りにつこう。"},

    { "next_scene_index": -1, "type": "scene change", "background": "road01" },
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "-翌日-"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "まるでそうしないことが不自然であるかのように、\nやはり{$B_name}と一緒に登校している。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "ねえねえ。\n今日って何の日か知っとるー？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "4月3日。\n4と3で、「シーサーの日」だな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "ええー？\n何言うとんのー？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "もっと{$player_name}くんにとって\n大事な日があるやろ？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "自分で言う奴がいるか。\n帰りに渡そうかと思ってたけど、コレ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "俺はプレゼントを渡した。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "うわー！これめっちゃ欲しかったんやよね。\n大事に使う。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "喜んでもらえたみたいで一安心だ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "こんなに良い物をくれた{$player_name}くんには、\n私とデートできる権利をあげます！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "デ、デート！？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "そんなに驚かんくても。\n週末空いとる？天気良さそうやしどっか行こ！"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "週末ならOKだよ。\nどっか行きたいところある？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "{$player_name}くん、決めて。\n県内ならどこでもいいよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$player_name}", "message": "そうだなあ…。\n「ココ」に行かないか？"},
    { "next_scene_index": -1, "type": "question", "background": "store", "options": ["スペイン村", "アメリカ村", "ドイツ村"], "answer": 0, "answer_next_scene_index": 275, "incorrect_next_scene_index": 272 },
    { "next_scene_index": -1, "type": "dark dialogue", "background": "road01", "speaker": null, "message": "「私、こんな{$player_name}くん嫌や…！」\n{$B_name}は泣きながら、俺のそばから走り去った。プレゼントも俺も置き去りにされた。\n\n「好感度アップ」からは、ほど遠い結果になった。こうなることならプレゼントなんて渡さなきゃよかった。\nそもそも{$C_name}が言い出したんじゃないか。あいつ、許せない。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "road01", "speaker": null, "message": "俺は登校中の{$C_name}の背後を取った。\nたまたま持っていた果物ナイフを突き付けた。\n\n「{$player_name}、こういう奴やったんやな」\n{$C_name}は果物ナイフを奪い、俺に向けてきた。"},
    { "next_scene_index": 270, "type": "bad end", "h2": "BAD END 6", "message": "{$player_name}は友人に刺されてしまいました。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "スペイン村！私も行きたいって思っとった。\n{$player_name}くん、エスパー？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "インスタ映えする写真いっぱい撮るん、\nめっちゃ楽しみ。"},
    { "next_scene_index": -1, "type": "supplement", "h2": "三重のスペイン\n「志摩スペイン村」", "message": "志摩スペイン村は待ち時間ゼロで普通に楽しめてしまうテーマパークです。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": "{$B_name}", "message": "じゃあ「しあさって」の午前8時半、\n駅で待ち合わせね。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "とんとん拍子にデートの予定が\n決まってしまった。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "子どもの頃の地区旅行以来のスペイン村。\nあの時も{$B_name}と一緒に回ったっけ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "road01", "speaker": null, "message": "昔の記憶が、脳裏に鮮明に蘇る。\nあの頃は結構賑わってたよなあ。"},

    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "それから数日間、\n俺の頭の中はデートのことでいっぱいになっていた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "あの日、{$B_name}は\n「しあさって」の午前8時半集合って言ってたよな。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "あの日は水曜日だったから、\n「しあさって」は……"},
    { "next_scene_index": -1, "type": "question", "background": "store", "options": ["金曜日", "土曜日", "日曜日"], "answer": 2, "answer_next_scene_index": 301, "incorrect_next_scene_index": 286 },

    { "next_scene_index": -1, "type": "scene change", "background": "station01" },
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "ついにデート当日。\n少し早めに駅に着いた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "村内を回る計画は入念に練った。\n今日は完璧に違いない。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "午前9時。\nまだ{$B_name}は来ない。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "{$B_name}にメッセージを入れた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "午前9時半。\n既読は未だに付かない。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "さすがに遅いし、連絡もない。\nどこかで災難に遭ってなければいいが。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "午前11時。\nまだ{$B_name}は来ない。連絡もつかない。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station01", "speaker": null, "message": "正午。\n{$B_name}の家に向かってみることにした。"},
    { "next_scene_index": -1, "type": "scene change", "background": "home_outside" },
    { "next_scene_index": -1, "type": "dialogue", "background": "home_outside", "speaker": null, "message": "チャイムを鳴らしたが、誰も出ない。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "どうなっているんだ。\nどこかで並行世界にでも迷い込んだというのか。\nしかし俺と{$B_name}はしっかりこの世界に存在している。\n一体どういう手違いがあったというのか。デートはエイプリルフールの嘘だったのだろうか。いや、4月3日に約束をしたしそれはない。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "home_outside", "speaker": "{$B_name}", "message": "夕方頃まで{$B_name}の家の前に居座った。\n本当に、どうなっているんだ。わけがわからない。\n\n俺は発狂した。"},
    { "next_scene_index": -1, "type": "dark dialogue", "background": "home_outside", "speaker": null, "message": "あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"},
    { "next_scene_index": 284, "type": "bad end", "h2": "BAD END 7", "message": "{$player_name}は通報され、逮捕されてしまいました。"},

    { "next_scene_index": -1, "type": "scene change", "background": "station02" },
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": null, "message": "ついにデート当日。\n少し早めに駅に着いた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": "{$B_name}", "message": "おまたせ～！\n待った？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": "{$player_name}", "message": "いや、さっき着いたところだよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": null, "message": "私服姿の{$B_name}は眩しすぎて、\nいつも以上に直視できない。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": "{$player_name}", "message": "じゃあ、行こっか。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": "{$B_name}", "message": "ちょっとー、\n何か言うことないん？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": "{$player_name}", "message": "…服、可愛いと思うよ。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": "{$B_name}", "message": "何か言わせたみたいになっちゃった。\n服だけ～？"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": "{$player_name}", "message": "行くよ！"},
    { "next_scene_index": -1, "type": "supplement", "h2": "しあさっては\n明後日の2日後", "message": "三重では「あした・あさって・ささって・しあさって」の順で日を数えます(地域差あり)。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": null, "message": "俺たちはデートに出かけた。"},
    { "next_scene_index": -1, "type": "dialogue", "background": "station02", "speaker": null, "message": "これをきっかけに俺たちは付き合うようになり、\n高校を卒業して数年後、結婚した。"},
    { "next_scene_index": -1, "type": "good end"},
];

const names = { "B": ["アイ", "アカリ", "ヒナタ", "メグ", "メイ", "サヨ", "ヤヒロ"], "C": ["コウ", "ツカサ", "ケン", "アカト", "剣持"] };
const background_img = {
    "home_outside": "home.jpg",
    "living": "home02.jpg",
    "room01": "room01.jpg",
    "room02": "room02.jpg",
    "road01": "road01.jpg",
    "school_entrance": "school01.jpg",
    "school_classroom": "school02.jpg",
    "school_garden": "school03.jpg",
    "store": "store.jpg",
    "station01": "station01.jpg",
    "station02": "station02.jpg",
    "shopping": "shopping.jpg"
}
const character_img = {
    "？？？": "silhouette1.png",
    "{$B_name}": "silhouette1.png",
    "{$C_name}": "silhouette2.png",
    "親": "silhouette3.png"
}

const other_img_files = 
["light_bulb.png", "logo.png", "next_allow.png", "next_allow02.png"]

const message_animation_interval = 7;